name 'pan'
maintainer 'Edmund Haselwanter'
maintainer_email 'me@ehaselwanter.com'
license 'Apache2'
description 'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version '1.1.0'
