name 'pan'
maintainer 'Infralovers'
maintainer_email 'team@infralovers.com'
license 'Apache2'
description 'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version '1.2.0'
